fullnameOverride: green-guestbook
nameOverride: green-guestbook
image:
  repository: nginx
  tag: latest
description: This is Green version of Guestbook application

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Canary-Ip"
    nginx.ingress.kubernetes.io/canary-by-header-value: "42.115.25.145"
    "nginx.ingress.kubernetes.io/custom-headers": "ingress-nginx/custom-headers"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
      more_set_headers "X-Canary: $remote_addr";
      proxy_set_header X-Canary-Ip $remote_addr;
  path: /
  hosts:
    - host: guestbook.pb-ha.ifs.fcam.vn
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: guestbook-tls
      hosts:
        - guestbook.pb-ha.ifs.fcam.vn