fullnameOverride: green-guestbook
nameOverride: green-guestbook
image:
  repository: nginx
  tag: latest
description: This is Green version of Guestbook application

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-by-header: "X-Real-IP"
    nginx.ingress.kubernetes.io/canary-by-header-value: "42.115.25.145"
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/modsecurity-transaction-id: "$request_id"
    nginx.ingress.kubernetes.io/modsecurity-snippet: |
      SecRule REQUEST_METHOD "@rx .*" \
        "id:1001,phase:1,log,deny,status:403,msg:'Potential TLS handshake or non-HTTP request detected',\
        chain"
      SecRule REQUEST_URI "@beginsWith %{tx.unicode.escape} \x16\x03\x01" \
        "t:none"
    nginx.ingress.kubernetes.io/configuration-snippet: |
       more_set_input_headers -r X-Forwarded-For $remote_addr;
       more_set_input_headers -r X-Real-Ip $remote_addr;
  path: /
  hosts:
    - host: guestbook.pb-ha.ifs.fcam.vn
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: guestbook-tls
      hosts:
        - guestbook.pb-ha.ifs.fcam.vn