fullnameOverride: blue-guestbook
nameOverride: blue-guestbook

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: ingress-nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
  path: /
  hosts:
    - host: guestbook.pb-ha.ifs.fcam.vn
      paths:
          - /
  tls:
    - secretName: guestbook-tls
      hosts:
        - guestbook.pb-ha.ifs.fcam.vn